In [1]:
#importing libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#to avoid warnings:
import warnings
warnings.filterwarnings('ignore')

#to display all rows and columns:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [2]:
#import dataset:
df=pd.read_csv(r'C:\Users\VISHAL\New folder\User Interface\data\exported_data\EncodedData.csv',header=0)
df.head(10)

loan_amnt  term  int_rate  installment  grade  sub_grade  emp_length  \
0     5000.0     0     10.65       162.87      1          6           1   
1     2500.0     1     15.27        59.83      2         13          10   
2     2400.0     0     15.96        84.33      2         14           1   
3    10000.0     0     13.49       339.31      2         10           1   
4     3000.0     1     12.69        67.79      1          9           0   
5     5000.0     0      7.90       156.46      0          3           3   
6     7000.0     1     15.96       170.08      2         14           8   
7     3000.0     0     18.64       109.43      4         20           9   
8     5600.0     1     21.28       152.39      5         26           4   
9     5375.0     1     12.69       121.45      1          9          10   

   home_ownership  annual_inc  verification_status     issue_d  purpose  \
0               3     24000.0                    2  2011-12-01        1   
1               3     30000.0                    0  2011-12-01        0   
2               3     12252.0                    1  2011-12-01       11   
3               3     49200.0                    0  2011-12-01        9   
4               3     80000.0                    0  2011-12-01        9   
5               3     36000.0                    0  2011-12-01       13   
6               3     47004.0                    1  2011-12-01        2   
7               3     48000.0                    0  2011-12-01        0   
8               2     40000.0                    0  2011-12-01       11   
9               3     15000.0                    2  2011-12-01        9   

   addr_state    dti  delinq_2yrs  inq_last_6mths  open_acc  pub_rec  \
0           3  27.65          0.0             1.0       3.0      0.0   
1          10   1.00          0.0             5.0       3.0      0.0   
2          14   8.72          0.0             2.0       2.0      0.0   
3           4  20.00          0.0             1.0      10.0      0.0   
4          37  17.94          0.0             0.0      15.0      0.0   
5           3  11.20          0.0             3.0       9.0      0.0   
6          27  23.51          0.0             1.0       7.0      0.0   
7           4   5.35          0.0             2.0       4.0      0.0   
8           4   5.55          0.0             2.0      11.0      0.0   
9          43  18.08          0.0             0.0       2.0      0.0   

   revol_bal  revol_util  total_acc  initial_list_status  out_prncp  \
0    13648.0        83.7        9.0                    0       0.00   
1     1687.0         9.4        4.0                    0       0.00   
2     2956.0        98.5       10.0                    0       0.00   
3     5598.0        21.0       37.0                    0       0.00   
4    27783.0        53.9       38.0                    0     766.90   
5     7963.0        28.3       12.0                    0       0.00   
6    17726.0        85.6       11.0                    0    1889.15   
7     8221.0        87.5        4.0                    0       0.00   
8     5210.0        32.6       13.0                    0       0.00   
9     9279.0        36.5        3.0                    0       0.00   

   out_prncp_inv   total_pymnt  total_rec_prncp  total_rec_int  \
0           0.00   5861.071414          5000.00         861.07   
1           0.00   1008.710000           456.46         435.17   
2           0.00   3003.653644          2400.00         603.65   
3           0.00  12226.302212         10000.00        2209.33   
4         766.90   3242.170000          2233.10        1009.07   
5           0.00   5631.377753          5000.00         631.38   
6        1889.15   8136.840000          5110.85        3025.99   
7           0.00   3938.144334          3000.00         938.14   
8           0.00    646.020000           162.02         294.94   
9           0.00   1476.190000           673.48         533.42   

   total_rec_late_fee  last_pymnt_amnt  collectio

In [3]:
#copy dataset in another file:
df1=df.copy()
df1.head(10)

loan_amnt  term  int_rate  installment  grade  sub_grade  emp_length  \
0     5000.0     0     10.65       162.87      1          6           1   
1     2500.0     1     15.27        59.83      2         13          10   
2     2400.0     0     15.96        84.33      2         14           1   
3    10000.0     0     13.49       339.31      2         10           1   
4     3000.0     1     12.69        67.79      1          9           0   
5     5000.0     0      7.90       156.46      0          3           3   
6     7000.0     1     15.96       170.08      2         14           8   
7     3000.0     0     18.64       109.43      4         20           9   
8     5600.0     1     21.28       152.39      5         26           4   
9     5375.0     1     12.69       121.45      1          9          10   

   home_ownership  annual_inc  verification_status     issue_d  purpose  \
0               3     24000.0                    2  2011-12-01        1   
1               3     30000.0                    0  2011-12-01        0   
2               3     12252.0                    1  2011-12-01       11   
3               3     49200.0                    0  2011-12-01        9   
4               3     80000.0                    0  2011-12-01        9   
5               3     36000.0                    0  2011-12-01       13   
6               3     47004.0                    1  2011-12-01        2   
7               3     48000.0                    0  2011-12-01        0   
8               2     40000.0                    0  2011-12-01       11   
9               3     15000.0                    2  2011-12-01        9   

   addr_state    dti  delinq_2yrs  inq_last_6mths  open_acc  pub_rec  \
0           3  27.65          0.0             1.0       3.0      0.0   
1          10   1.00          0.0             5.0       3.0      0.0   
2          14   8.72          0.0             2.0       2.0      0.0   
3           4  20.00          0.0             1.0      10.0      0.0   
4          37  17.94          0.0             0.0      15.0      0.0   
5           3  11.20          0.0             3.0       9.0      0.0   
6          27  23.51          0.0             1.0       7.0      0.0   
7           4   5.35          0.0             2.0       4.0      0.0   
8           4   5.55          0.0             2.0      11.0      0.0   
9          43  18.08          0.0             0.0       2.0      0.0   

   revol_bal  revol_util  total_acc  initial_list_status  out_prncp  \
0    13648.0        83.7        9.0                    0       0.00   
1     1687.0         9.4        4.0                    0       0.00   
2     2956.0        98.5       10.0                    0       0.00   
3     5598.0        21.0       37.0                    0       0.00   
4    27783.0        53.9       38.0                    0     766.90   
5     7963.0        28.3       12.0                    0       0.00   
6    17726.0        85.6       11.0                    0    1889.15   
7     8221.0        87.5        4.0                    0       0.00   
8     5210.0        32.6       13.0                    0       0.00   
9     9279.0        36.5        3.0                    0       0.00   

   out_prncp_inv   total_pymnt  total_rec_prncp  total_rec_int  \
0           0.00   5861.071414          5000.00         861.07   
1           0.00   1008.710000           456.46         435.17   
2           0.00   3003.653644          2400.00         603.65   
3           0.00  12226.302212         10000.00        2209.33   
4         766.90   3242.170000          2233.10        1009.07   
5           0.00   5631.377753          5000.00         631.38   
6        1889.15   8136.840000          5110.85        3025.99   
7           0.00   3938.144334          3000.00         938.14   
8           0.00    646.020000           162.02         294.94   
9           0.00   1476.190000           673.48         533.42   

   total_rec_late_fee  last_pymnt_amnt  collectio

In [4]:
#no. of columns and rows
df1.shape

(855969, 35)

### Splitting Data

In [5]:
#Splitting data into train and test, train data-(June 2007 - May 2015) and test data-(June 2015 - Dec 2015)
train=df1[df1['issue_d']<'2015-06-01']
test=df1[df1['issue_d']>='2015-06-01']

In [6]:
#check the shape of train and test data:
print(train.shape)
print(test.shape)

(598978, 35)
(256991, 35)


In [7]:
train=train.drop('issue_d',axis=1)

test=test.drop('issue_d',axis=1)

In [8]:
#check the shape of train and test data:
print(train.shape)
print(test.shape)

(598978, 34)
(256991, 34)


In [9]:
#now we divide train and test into X_train, Y_train, X_test, Y_test
X_train=train.iloc[:,:-1]
Y_train=train.iloc[:,-1]
X_test=test.iloc[:,:-1]
Y_test=test.iloc[:,-1]

In [10]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(598978, 33)
(598978,)
(256991, 33)
(256991,)


In [11]:
train.head()

loan_amnt  term  int_rate  installment  grade  sub_grade  emp_length  \
0     5000.0     0     10.65       162.87      1          6           1   
1     2500.0     1     15.27        59.83      2         13          10   
2     2400.0     0     15.96        84.33      2         14           1   
3    10000.0     0     13.49       339.31      2         10           1   
4     3000.0     1     12.69        67.79      1          9           0   

   home_ownership  annual_inc  verification_status  purpose  addr_state  \
0               3     24000.0                    2        1           3   
1               3     30000.0                    0        0          10   
2               3     12252.0                    1       11          14   
3               3     49200.0                    0        9           4   
4               3     80000.0                    0        9          37   

     dti  delinq_2yrs  inq_last_6mths  open_acc  pub_rec  revol_bal  \
0  27.65          0.0             1.0       3.0      0.0    13648.0   
1   1.00          0.0             5.0       3.0      0.0     1687.0   
2   8.72          0.0             2.0       2.0      0.0     2956.0   
3  20.00          0.0             1.0      10.0      0.0     5598.0   
4  17.94          0.0             0.0      15.0      0.0    27783.0   

   revol_util  total_acc  initial_list_status  out_prncp  out_prncp_inv  \
0        83.7        9.0                    0        0.0            0.0   
1         9.4        4.0                    0        0.0            0.0   
2        98.5       10.0                    0        0.0            0.0   
3        21.0       37.0                    0        0.0            0.0   
4        53.9       38.0                    0      766.9          766.9   

    total_pymnt  total_rec_prncp  total_rec_int  total_rec_late_fee  \
0   5861.071414          5000.00         861.07                0.00   
1   1008.710000           456.46         435.17                0.00   
2   3003.653644          2400.00         603.65                0.00   
3  12226.302212         10000.00        2209.33               16.97   
4   3242.170000          2233.10        1009.07                0.00   

   last_pymnt_amnt  collections_12_mths_ex_med  application_type  \
0           171.62                         0.0                 0   
1           119.66                         0.0                 0   
2           649.91                         0.0                 0   
3           357.48                         0.0                 0   
4            67.79                         0.0                 0   

   acc_now_delinq  tot_coll_amt    tot_cur_bal  default_ind  
0             0.0    225.412882  139766.247529            0  
1             0.0    225.412882  139766.247529            1  
2             0.0    225.412882  139766.247529            0  
3             0.0    225.412882  139766.247529            0  
4             0.0    225.412882  139766.247529            0

In [12]:
train.columns

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'purpose', 'addr_state', 'dti', 'delinq_2yrs', 'inq_last_6mths',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'application_type',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'default_ind'],
      dtype='object')

### Model Building

### Logistic Model

In [13]:
#we have to import 'logisticRegression' from 'sklearn.linear_model':
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()
log_model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
Y_pred=log_model.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),

In [15]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(Y_test,Y_pred))
print()
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[256680      0]
 [    63    248]]

0.9997548552283932
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    256680
           1       1.00      0.80      0.89       311

    accuracy                           1.00    256991
   macro avg       1.00      0.90      0.94    256991
weighted avg       1.00      1.00      1.00    256991



### SGD Classifier

In [16]:
from sklearn.linear_model import SGDClassifier
classifier_SGD=SGDClassifier(loss="log",random_state=10,alpha=0.01,max_iter=1000, shuffle=True,early_stopping=True,
                             n_iter_no_change=3)

classifier_SGD.fit(X_train,Y_train)

Y_pred=classifier_SGD.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[256677      3]
 [   107    204]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    256680
           1       0.99      0.66      0.79       311

    accuracy                           1.00    256991
   macro avg       0.99      0.83      0.89    256991
weighted avg       1.00      1.00      1.00    256991

Accuracy of the model:  0.9995719694464008


### Decision Tree

In [18]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree = DecisionTreeClassifier(criterion="gini",random_state=10)

model_DecisionTree.fit(X_train,Y_train)
Y_pred = model_DecisionTree.predict(X_test)
print(Y_pred)

[1 1 1 ... 0 0 0]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 77486 179194]
 [     1    310]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.30      0.46    256680
           1       0.00      1.00      0.00       311

    accuracy                           0.30    256991
   macro avg       0.50      0.65      0.23    256991
weighted avg       1.00      0.30      0.46    256991

Accuracy of the model:  0.3027187722527248


### Tune Decision Tree

In [30]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree1 = DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best",min_samples_leaf=5,
                                            max_depth=8,min_samples_split=10,max_leaf_nodes=170)

model_DecisionTree1.fit(X_train,Y_train)
Y_pred = model_DecisionTree1.predict(X_test)
print(Y_pred)

[1 1 1 ... 0 0 0]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[130574 126106]
 [     2    309]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.51      0.67    256680
           1       0.00      0.99      0.00       311

    accuracy                           0.51    256991
   macro avg       0.50      0.75      0.34    256991
weighted avg       1.00      0.51      0.67    256991

Accuracy of the model:  0.5092902086065271


### Random Forest

In [24]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=30, random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[134999 121681]
 [     5    306]]
0.5264970368612131
              precision    recall  f1-score   support

           0       1.00      0.53      0.69    256680
           1       0.00      0.98      0.01       311

    accuracy                           0.53    256991
   macro avg       0.50      0.75      0.35    256991
weighted avg       1.00      0.53      0.69    256991



In [1]:
#importing model using pickle:
import pickle

In [32]:
#saving model:
pickle.dump(log_model,open(r'C:\Users\VISHAL\Web Deployment\Loan Prediction\model\log_model.pkl','wb'))
pickle.dump(classifier_SGD,open(r'C:\Users\VISHAL\Web Deployment\Loan Prediction\model\sgd_model.pkl','wb'))
pickle.dump(model_DecisionTree1,open(r'C:\Users\VISHAL\Web Deployment\Loan Prediction\model\dt_model.pkl','wb'))
pickle.dump(model_RandomForest,open(r'C:\Users\VISHAL\Web Deployment\Loan Prediction\model\rf_model.pkl','wb'))

In [2]:
model=pickle.load(open(r'C:\Users\VISHAL\Web Deployment\Loan Prediction\model\log_model.pkl','rb'))

In [3]:
print(model.predict([[5000.0,0,10.65,162.87,1,6,1,3,24000.0,2,1,3,27.65,0.0,1.0,3.0,0.0,13648.0,83.7,9.0,0,0.0,0.0,5861.071414,
                      5000.00,861.07,0.00,171.62,0.0,0,0.0,225.412882,139766.247529]]))

[0]


In [4]:
print(model.predict([[5000,0,11,163,1,6,1,3,24000,2,1,3,28,0,1,3,0,13648,84,9,0,0,0,5861,
                      5000,861,0,172,0,0,0,225,139766]]))

[0]


In [3]:
print(model.predict([[2500,1,15,60,2,13,10,3,30000,0,0,10,1,0,5,3,0,1687,9,4,0,0,0,
                      1009,456,435,0,120,0,0,0,225,139766]]))

[1]
